### ISSUE TITLE
this.setState({

### ISSUE THREAD

**Issue by hibiINOVA** [Flaque/quirk#1012]
Do not use setState in componentDidUpdate (react/no-did-update-set-state)

**Comment by irpuliy** [comment]
Hi. I  changed the this.setState to the constructor() . Please check out what I have done.
Here is the link to the edits I did. All the edits are in src/tabBar.tsk.
[https://github.com/irpuliy/quirk-fixing-this.setState-in-TabBar.tsk](url)
