### ISSUE TITLE
Lost edits while scrolling

### ISSUE THREAD

**Issue by YoavGivati** [Flaque/quirk#106]
Repro:
1. Save a new entry
2. Open it back up and edit it
3. edit some fields
4. Try to scroll starting from anywhere in the top bar and dragging down
5. It starts scrolling the entire edit screen to reveal the list page and when you lift you finger it, even if you drag it back up before lifting, it goes back to the list page and loses all the edits.

Expected: There should be a more explicit way to cancel edits. Eg:
- a confirmation modal
- a button that says cancel
- it should not cancel on scroll

![07FD3032-DEAE-4322-9BA9-2BD1B28AD731](https://user-images.githubusercontent.com/707633/56813192-5e657f00-67f1-11e9-8a0d-6c646519a21b.jpeg)

**Comment by Flaque** [comment]
Hmm, I'm confused about what you mean by "try to scroll by touching the hamburger button and dragging the page" and that "It starts scrolling the entire edit screen to reveal the list page." What do you mean by **reveal the list page**?

Also, if you wind up in the list page and then come back, aren't your edits still there? (They should be, otherwise this is a bigger bug).

**Comment by YoavGivati** [comment]
> "try to scroll by touching the hamburger button and dragging the page

You can actually cancel edits by dragging any part of the top bar down I've updated the top comment.

1. while editing an existing item
![Screen Shot 2019-04-26 at 6 24 37 PM](https://user-images.githubusercontent.com/707633/56843026-c303f680-6850-11e9-8641-6ec1cbce3483.png)
![Screen Shot 2019-04-26 at 6 24 50 PM](https://user-images.githubusercontent.com/707633/56843031-cc8d5e80-6850-11e9-8db5-8cf42eac77c5.png)

2. drag down the `quirk` heading at the top or the `list` button in the top right. Doing so will reveal the list underneath
![Screen Shot 2019-04-26 at 6 25 15 PM](https://user-images.githubusercontent.com/707633/56843047-eb8bf080-6850-11e9-8311-5bd20f5ba6cb.png)

3. If you release it and allow the scroll the `edit item` card will swipe all the way down and all changes will be lost. (clicking back into the item and trying to edit again all changes you made before swiping it away will be gone)

**Comment by Flaque** [comment]
Ah this is definitely a bug, though not 100% sure how to fix it yet. Will look into it, thanks for reporting 🙏🙏🙏🙏🙏

**Comment by Flaque** [comment]
Hey does this still happen in the new flow?
