### ISSUE TITLE
Create better screenshots for app stores

### ISSUE THREAD

**Issue by gianpaj** [Flaque/quirk#108]
This what appears from an iPhone 6 on the Irish App Store

<img width="360" src="https://user-images.githubusercontent.com/899175/56941006-502da080-6b1a-11e9-964c-cd95da7ccd1e.PNG" />

I believe you need to resize the screenshots for `5.5-inch (iPhone 6s Plus, iPhone 7 Plus, iPhone 8 Plus)` and upload them on the App Store Connect (or maybe via `fastlane`).
By default, the 4.7-inch devices (iPhone 6, etc) use the scaled 5.5-inch screenshots.

https://help.apple.com/app-store-connect/#/devd274dd925

**Comment by Flaque** [comment]
I've been putting this off because it's a crazyyyyy huge pain to do for all the screen sizes. We end up spending like literal hours every update trying to futz with all the various screen-sizes (especially on Android). 

So I just picked a single size and then made stuff a little smaller. 😭 Not the best, but also much easier

**Comment by gianpaj** [comment]
I believe the size is not the issue here. Is the that the current [screenshots](https://github.com/Flaque/quirk/tree/master/fastlane/screenshots/en-US) are not appearing for smaller size devices on the App Store.

I discovered this myself for my app only few days ago 😅

<img width="741" alt="Screenshot 2019-04-30 at 11 39 16" src="https://user-images.githubusercontent.com/899175/56949838-a3b0e600-6b3c-11e9-86b2-b62bb341ff79.png">

**Comment by Flaque** [comment]
Oh, those are super outdated 😅I should probably get rid of them from the repo. This is what the current screenshots look like: 

<img width="923" alt="Screen Shot 2019-04-30 at 9 30 29 AM" src="https://user-images.githubusercontent.com/5942769/56977718-aefb1600-6b2a-11e9-875d-7242dfc1c71c.png">

**Comment by gianpaj** [comment]
Oh. Then, I actually prefer the old screenshots (the ones in the repo) as, on the current ones, the text inside the iPhone frame is too small IMHO.

Also, in my opinion, the marketing taglines are not super great.

For example the first:
<img width="230" src="https://is3-ssl.mzstatic.com/image/thumb/Purple123/v4/65/75/9d/65759d32-57a7-e733-23e6-e04519b96743/mzl.cvaebatd.png/460x0w.jpg" />
> quirk is a free open-source app for Cognitive Behavioural Therapy

doesn't say anything about the benefits of the app.
An app being open-source doesn't make much difference to the end user. Maybe it says something about that there's a community behind it or that or that's it's transparent and doesn't sell your data, but I would say that's it's not the **number one** benefit.
I'm not a marketing person so maybe it would be better to find somebody to consult on these.

Perhaps it should say something like "Record your thoughts" and then also explain Cognitive Behavioural Therapy. Which, I know, it's not easy in only a few words.

Anyway, just a few thoughts to get more folks to download the app and get the benefits from it :)

**Comment by Flaque** [comment]
> An app being open-source doesn't make much difference to the end user. Maybe it says something about that there's a community behind it or that or that's it's transparent and doesn't sell your data, but I would say that's it's not the number one benefit.

This is a really good point, I think I've been hanging out with too many developers. **Let's change it.**

I do want to use the new screenshots, since they're up to date and everything. 

But I'm very open to suggestions on the taglines or design of screenshot layouts should be instead.

**Comment by gianpaj** [comment]
A resource I found:
- [freeCodeCamp.org- UX best practices: How to design scannable app screenshots](https://medium.freecodecamp.org/ux-best-practices-how-to-design-scannable-app-screenshots-89e370bf433e)
