### ISSUE TITLE
Change language in settings screen

### ISSUE THREAD

**Issue by siddise** [Flaque/quirk#115]
There should be a possibility to change the language in the app in the settings screen. 
I would think that users might have a system language that is different than their native language or the language that they think with.

**Comment by Flaque** [comment]
Hmm, are you having this use case? 

What's the device language and the app language you'd like to be using? Also why do you keep the device in a different language?

**Comment by siddise** [comment]
I don't know if this is a normal use case, but in my case I usually have my devices in english even though I'm norwegian. Mostly becuase most guides and tutorials online are written in english and refer to english system settings.
