### ISSUE TITLE
Can you support Right-to-Left Languages?

### ISSUE THREAD

**Issue by nabsul** [Flaque/quirk#120]
I really enjoyed listening to your changelog episode :-)

I would like to contribute an Arabic translation of this app, and I know folks who might be willing to contribute Hebrew.

Problem is, both of these languages are RTL (right to left). Is this scenario supported in your internationalization?

**Comment by nabsul** [comment]
Based on the readme, it sounds like @devinroche should know the answer 😀

**Comment by devinroche** [comment]
Hi sorry I am traveling in Brazil right now so wifi has been a bit spotty! Currently we dont support RTL languages.

From reading into [RTL support](https://facebook.github.io/react-native/blog/2016/08/19/right-to-left-support-for-react-native-apps) it seems like we may need to change most of the styling to support this as well. Would this be something you would be interested in helping out with? 

this is a super cool idea!

**Comment by nabsul** [comment]
I've never done this, but I'll look into it if/when I get a chance.

**Comment by Flaque** [comment]
On the roadmap; see #124

**Comment by nabsul** [comment]
Awesome, I can't make any commitments, but if there are any conversations to be had on this topic I'd love to participate.

**Comment by majdal** [comment]
I only just heard the Changelog episode, and I'm happy to contribute translation for Arabic, assuming that there is rtl support.
