### ISSUE TITLE
Anyway to run this on desktop?

### ISSUE THREAD

**Issue by iamLoi** [Flaque/quirk#122]
This app is really cool! I do have a question: is there anyway to run this on a desktop instead of just iOS? Some people don't like the typing experience on phones (like me) and would enjoy the exact some app but for desktop where they can go deeper into their emotions. Anyway this can be ported into a desktop version (Mac/PC)?

**Comment by Flaque** [comment]
Nah, probably not. But I am considering making a purely web version which might solve this for ya.
