### ISSUE TITLE
I'm going to be working on Quirk full-time.

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#124]
If you've been following the Quirk project for awhile, you might have noticed a trend:

<img width="574" alt="Screen Shot 2019-06-07 at 2 50 48 PM" src="https://user-images.githubusercontent.com/5942769/59137877-c1911800-893e-11e9-9277-bfffae3a9fb3.png">

I get a whole ton of work done on Quirk, then something comes up in my life, and work on Quirk dies down. Today is the end of that, because I'm now working on Quirk full time. 

## Subscription

In order to support this, I'm going to add a small monthly subscription with an undetermined price. This subscription goes to keeping the app on the store and paying myself; before I was financing a lot of this through my own job.

**If you're already using Quirk, I'd like to thank you for your support. You'll be getting the app free, probably forever.**

### Why a Subscription?

When you start taking money from people, the monetization *becomes* your product. For example, Facebook isn't the product, Facebook ad's are the product. So we wanted to create a model where effort devoted to monetization meant more value to a Quirk user.

With a subscription, the product becomes all about retention. This fits really well with CBT. CBT works best when you actually do it. Which means that if you only use Quirk for a little while, you may end up thinking "oh CBT doesn't really work for me." 

But with a subscription, I can align the user's health with the financial interests of Quirk. If you're using Quirk and it's helping you, we get paid. Otherwise, we don't. 

## Rejected Models and Why We Rejected them

The following are models that we considered, but ultimately thought they wouldn't be good for people. 

### Freemium Model

At least at the moment, we don't have any plans to have a "purely" free model. This was _heavily_ what I wanted to do at first. I said Quirk was free and I _really_ really wanted it to be.

But after a _lot_ of examination, I couldn't find a single "freemium" product I actually liked. Every "free" version is awful. 

This happens because the developers have an incentive to make the product seem REALLY shiny so you download it and then make the free version quite crappy so you convert to paid. This tends to lead to really terrible products.

I'd rather build a _great_ product that costs money than a _bad_ product that's free. 

### Donations from Users

Many, many people have offered to donate to Quirk. So for awhile, we considered just making this an option to support ourself. 

The problem is that it sets up a financial incentive system that we think will make the product worse. When anyone can donate multiple times at variable rate, our product becomes about bugging people until they donate. 

Instead, we'd rather you just sign up and focus on CBT rather than on us begging you all the time.

### Outside Donors (501c Charity)

For awhile, we considered being a charity taking grant or fundraiser money. However, if we did this, our job would be to create grant applications and schmooze richer folks, not create the best CBT app.

### One time payment

With a one time payment, we would only be focused on Acquisition. Once someone has downloaded the app, we have no financial incentive to make it a good experience. This incentivizes Quirk to have "sneaky" marketing and disregard long-time users. 

### Ad Models

With an ad model, we're heavily incentivized to start collecting as much data on you as possible. Which, for an app that explicitly does not store your thoughts on any server, we thought this was absolutely not the right way to go.

## Quirk as a Company

Technically, this means Quirk has incorporated as a company with two founders, myself (Evan Conrad) and my brother who's been doing a lot of work behind the scenes. 

### First and foremost OSS

As much as possible, everything we build is open source. That's how we got started and we're pretty sure that's how we'll continue. 

### Open as Possible

As much as possible, everything about how we run things is pretty open. This includes stats about how many people use Quirk (6.5k active per month). 

### Create more value than captured

I'm really bad at Capitalism. And I don't want to be good at it. I'd rather create 10 times more value for people than what we're charging. 

## Roadmap

Working full time on Quirk, we can do a whole bunch of things. 

### Lock Screen

Easily the most requested feature, we'll be adding an optional lock screen.

### What-if-true Support

We'll be adding a smooth way to dig-down into your thoughts through an exercise called "what-if-true."

For example, let's say you're like me and are *terrified* about quitting your job to pursue Quirk. You might have something like:

- "If I quit my job and pursue Quirk, I might waste all of my savings"

You could ask "what if true" before trying to challenge it. Which might lead you down a chain like:

- "If true, then I might have to go back and get a software job again"
- "If true, then maybe people will think I'm a failure"

*Then* you can start challenging the thought. Because you've gotten to the root problem.

### Expanding language support

We'll likely be rewriting much of the way we do translations with hopeful support for left-right languages, syntax formatting, etc. We're also considering making it easier than editing a JSON file.

### Better explanations of cognitive distortions

There's *so* many cognitive distortions and it's really hard to tell in the moment which one you should be using. We have some multi-part solutions here about how to handle this. 

### Better navigation

Navigation is quite buggy and a bit confusing, we'd like to fix this.

### Much better on-boarding

Right now the on-boarding isn't *really* super great. People can often get passed it without knowing what they should do next.

### Education
At the moment, CBT isn't super well known. A whole group of people have _never_ heard of it, even when they should. And when they have heard of it, it's particularly difficult to learn "how" to do it. 

So we're also considering building more educational components. However, educational pieces don't belong heavily in the app. We'd like to keep it as simple as possible. 

So `quirk.fyi` will likely live up to its name more and more. 

### Research
Because Quirk is open, we can do a lot to help researchers study CBT "in the wild." This might mean creating a fork of Quirk _specifically_ for researchers.

**Comment by devinroche** [comment]
congrats dude! super exciting news!

**Comment by gkunthara** [comment]
Proud of you Evan!! I'm excited to see what the future holds with Quirk. Good luck and all the best!

**Comment by qazip** [comment]
I hate subscription models.. Another subscription on top of all the other ones.. However, I do understand the appeal from your side. Do you have any idea of the price of the subscription?

The issue with this is that you are creating a pay-wall for mental health.. It would be nice if you had some sort of program for "grandfathering" other users and for giving free access to those who really need it. Also, free trails are a must IMO.

Have you thought of a mix of donations/subscription? For example, say a "normal" job pays you 3k/month (sorry if this is low or high, it's just an example). You do the app subscription-based until you reach the 3k/month. Once you reach that, you offer it for free for X users. This idea needs to be polished.

Having said that, @Flaque, as long as you keep it open-source, I fully support you! I hope it works out, this really is a great app.

**Comment by nabsul** [comment]
Another thing to keep in mind when setting a price point is that $5 USD might be a cup of coffee in one country and dinner for two in another.

**Comment by Flaque** [comment]
@qazip It's either a subscription model an ad model :( And in an ad model, we're only incentivized to help advertisers. I'd much build something that helps folks. 

> pay-wall 

First, the goal is to be cheap but really high distribution. Not 100% sure what the price is, we'll test a single price and then raise and lower it in a number of different experiments to see what the "correct" price is. 

But in general, we want it to be a much, much cheaper than seeing a therapist. The goal is to make CBT for folks to deal with day-to-day problems, so we can prevent people from ever developing severe depression and anxiety. 

I started this because I _want_ it to be accessible. But it also has to... like _exist_ in order to be accessible at all. So _some_ form of monetization needs to happen otherwise we can't do it. 

> Grandfathering

We do! Users who are currently using quirk will get quirk free forever. (Kinda, we can really only do it if you keep it on your phone, if you delete quirk, send me a message and I'll see what I can do.)

> Users who really need it

The app stores make it difficult to give out "free" copies of in-app-purchases except either for testing or in grand-sweeping donations. So we'd like to try and give free-quirk to some charities that work with high-risk populations. If you know someone who works in this area, please send them my way!

> Donation/subscription model
First, this isn't really possible with the way Apple does it's pricing :( But also the issue with this model is it encourages us to abandon Quirk after it hits it's maximum price point.

It also limits our ability to make bigger investments that require hiring artists, videographers, psychiatrists, etc. We'd like to make more CBT education as well, but there's a number of things that aren't really possible with a small budget and 2 dudes. 

> keep it open-source

Of course! It's GPL anyway. Thanks for the support, we want to continue to make it better and not-dead! 

---

@nabsul Agreed! We're doing location based pricing, so more expensive regions will have more expensive prices. That said, we're currently just doing what Apple/Google Play suggests as prices, so if we're likely wildly expensive somewhere, please let us know!

**Comment by qazip** [comment]
> We do! Users who are currently using quirk will get quirk free forever. (Kinda, we can really only do it if you keep it on your phone, if you delete quirk, send me a message and I'll see what I can do.)

I meant a different grandfathering system. Something like the ability to offer a quirk subscription to someone in need. Either someone you know (for example, you buy a code and you give him the code, or just input his email or something) or just a "random" person: "Gift quirk to the community". This should be hard to do with the app shops though. 

You could also build a community around this app, that would be nice. But please, no social medial and/or anti-privacy bullshit. I just thought of a discourse forum and/or a matrix room. But probably not.

PS: You are obviously a gifted coder. If you ever decide to quit quirk, either because it's feature complete or because you got tired of it, you should try to make a gratitute app. Something like "five minute journal", but open source. I couldn't find anything like that in the FLOSS community. Gratitude, like CBT, seems to be incredibly powerful for ones mental health.

**Comment by Flaque** [comment]
> Something like the ability to offer a quirk subscription to someone in need. Either someone you know (for example, you buy a code and you give him the code, or just input his email or something) or just a "random" person: "Gift quirk to the community". 

Huh. That's a really good idea. Let me see if I can figure out a way to do that. I'm not 100% sure if it's possible on iOS, but it might be on Android. It's going into the research-roadmap. 

> You are obviously a gifted coder. If you ever decide to quit quirk, either because it's feature complete or because you got tired of it, you should try to make a gratitude app. 

I'll look into that. If Quirk does well, I'd prefer to expand into new products rather than shove everything into this app. So I'll keep this in the "new product" list.

**Comment by imtiyazalikhan** [comment]
this project has some error when I am using in command prompt , after searching in Visual studio code then I have see in the that there was not error in it so I have try it ones again but also I did not get the out put so  what can I do
