### ISSUE TITLE
Distortion description not appearing

### ISSUE THREAD

**Issue by gkunthara** [Flaque/quirk#126]
Should the distortion's description be next to the distortion's icon when viewing your list of thoughts? The grey box the icon sits in makes it seem like there should be text to follow it. I'm not sure if this is a bug or expected behavior, but I thought I'd call it out. 🙂I am on an iPhone X btw (not the XS or XR, just the base X).

![image](https://user-images.githubusercontent.com/9055394/59324620-84a58800-8c94-11e9-9d3a-5175adeb6fc8.png)

**Comment by Flaque** [comment]
Nah, this is expected. The bottom bar just the emojis for the distortions so you can visually see what type of distortions you're commonly experiencing. 

For example, you'll see a bunch of emojis if you select a bunch of distortions. 

Though having descriptions of distortions is an interesting idea. I'd love to come up with some "one-liners" for each distortion.

**Comment by gkunthara** [comment]
Ahh I see what you're saying. A one-liner, or some additional way to describe the distortion would be nice! 🙂
