### ISSUE TITLE
Thought Training Exercises

### ISSUE THREAD

**Issue by jonshern** [Flaque/quirk#130]
Not sure if this fits within the category of examples or training
In the feeling good book on pages 43 - 47 
They have examples with example answers 
And then on page 47 they have an answer key to help you classify the example thoughts.

This format is nice since it helps get you calibrated to types of cognitive distortions and which ones could apply. This would be awesome to get the uninitiated into the app without needing to first put down thoughts.

**Comment by Flaque** [comment]
We're considering building this, but in a different app. We'd like to keep Quirk itself small, but build other apps around it!
