### ISSUE TITLE
Grandfathering is not working on iOS

### ISSUE THREAD

**Issue by adamserafini** [Flaque/quirk#135]
I’ve been casually using quirk since it was originally posted to hacker news and now cannot use the app without subscribing. This in itself is not a problem except in the announcement about subscription it says existing users are grandfathered with free access but that’s not the case for me so something appears to not be working.

Opening the app takes me to a splash screen where the only option to proceed is to ‘get it’ (subscribe).

I haven’t uninstalled and reinstalled the app this is just the same version of the app I was using free before.

How is the grandfathering supposed to work on iOS?

**Comment by Flaque** [comment]
:( :( Did you use the app within the last month or so? If so, the app would grandfather you in. 

If not, you can send me an email and I'll give you a promocode. `ejc @ qurik . fyi`
