### ISSUE TITLE
Form doesn’t clear when editing and saving a thought

### ISSUE THREAD

**Issue by jzblee** [Flaque/quirk#145]
When opening a past entry and tapping Save & Finish in iOS, the saved thought is correctly displayed, but the text doesn’t get cleared from the form view. This seems to happen regardless of whether any property of the thought was modified or not.

Looks similar to #15, and was worked on in  49ff6a8a77dd07bced574a8b4f74183f4de8a07f.

**Comment by Flaque** [comment]
@jzblee do you have the newest version? Can you show me a screenshot of what you mean?

**Comment by jzblee** [comment]
@Flaque Yep, I've got 2.2.0. Here are the steps I took:

Edit an existing entry:
![IMG_5950](https://user-images.githubusercontent.com/12802389/61396699-dfb54500-a8fa-11e9-9bc4-fc440242a1c4.PNG)

Edit a value in the entry:
![IMG_5951](https://user-images.githubusercontent.com/12802389/61396708-e3e16280-a8fa-11e9-9aef-63615ca9da72.PNG)

Change the value and tap Save:
![IMG_5952](https://user-images.githubusercontent.com/12802389/61396713-e6dc5300-a8fa-11e9-82ef-49224236ef32.PNG)

Close the detail window:
![IMG_5953](https://user-images.githubusercontent.com/12802389/61396722-e9d74380-a8fa-11e9-88fa-5320fb7bf522.PNG)

Form is still uncleared:
![IMG_5954](https://user-images.githubusercontent.com/12802389/61396728-ecd23400-a8fa-11e9-9da3-d58508b66bb3.PNG)

**Comment by Flaque** [comment]
Oh woah, yes. Can reproduce, hold on I'm pretty sure I know how to fix it. Thanks for reporting!

**Comment by Flaque** [comment]
Cool, fixed. Close your app, reopen it and all should be good. 

I'll push up the commit that fixes it later, for whatever reason the public wifi seems to be blocking the port git uses on pushes. 😅

**Comment by jzblee** [comment]
Awesome, thanks! 😃

**Comment by Flaque** [comment]
No problem, thanks for reporting! 

![image](https://user-images.githubusercontent.com/5942769/61403077-bf9d6b80-a891-11e9-81ae-f02ae08a4a39.png)
