### ISSUE TITLE
Redo Translations with Fluent & Pontoon

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#146]
At the moment, the JSON file style of translations is basically unmaintainable. Adding or editing a new translation is a nightmare, and so I've just been letting the translations slide.

This is a solved problem though, we should move all the string assets into [Fluent](https://hacks.mozilla.org/2019/04/fluent-1-0-a-localization-system-for-natural-sounding-translations/) files and then setup a [Pontoon](https://mozilla-pontoon.readthedocs.io/en/latest/user/localizing-your-projects.html) instance.

**Comment by Jos512** [comment]
I appreciate the idea and motivation, but I doubt that a new file format (Fluent) is going to help get more/quicker translations.

For me personally it would be off putting, since I'd have to learn a new syntax. And somehow know what the variables names refer to (which makes it more abstract than simple string verbatim translation).

**Comment by Flaque** [comment]
This is less so about getting more/quicker translations and more so about a translated Quirk being... possible. 

At the moment, most of the translations in Quirk have died, mainly due to stuff I caused. 🤦‍♂️ Every time we add new text due to a new feature or a rework (nearly every day now), we rip out some of the old translations. 

Adding all the translations _back_ is super difficult since we have to go add a json-property to _every single_ file.

But if any of that text is dynamic or has **bold** or _italics_, then we have to add like 4 json properties to each language; which leads to untranslatable sections of text in multiple languages. 

For example, let's say I want to translate this phrase to french:
```
I like **blue** dogs.
```

To do add that to our current system, we have to go to _every_ json file and add something like:
```json
{
  "i_like_first_part": "I like",
  "i_like_emphasis": "blue",
  "i_like_last_part": "dogs"
}
```

Then, if we wanted to translate that to french, we'd end up doing something like this:
```json
{ 
  "i_like_first_part": "J'adore",
  "i_like_emphasis": "blues",
  "i_like_last_part": "les chiens"
}
```

Which would give us something quite incorrect: 
```
J'adore **blues** les chiens.
```

But in a Platoon + Fluent system, we'd just have a GUI that anyone could use (so we can allow translations from folks that don't know git). That GUI supports translations like that in what looks a _lot_ like HTML.

<img width="856" alt="Screen Shot 2019-07-30 at 9 31 36 AM" src="https://user-images.githubusercontent.com/5942769/62148089-dc806880-b2ad-11e9-9b53-83289eec1af7.png">

**Comment by Jos512** [comment]
> At the moment, most of the translations in Quirk have died, mainly due to stuff I caused. 

Nah, I wouldn't say that. I think it might be a problem of too little information and people not knowing new translations are needed.

> we'd just have a GUI that anyone could use (so we can allow translations from folks that don't know git)

I didn't knew that. That's a big advantage!
