### ISSUE TITLE
Menu buttons & graphics cut off on the right side (iPhone SE)

### ISSUE THREAD

**Issue by harritaylor** [Flaque/quirk#150]
This issue doesn't reduce the functionality of the app, it just feels a little cramped. I also have the autocomplete bar on, which cuts off the submit button when entering thoughts. 
Love the concept so far though!

**Comment by Flaque** [comment]
Thanks for reporting! We're working on fixing this, it keeps cropping up! 😬

**Comment by darkhist** [comment]
Hey, I hope this isn't redundant, but I also noticed text clipping when using anything larger than the default text size on my iPhone X. Although this doesn't reduce the functionality of the app, it makes the app a bit difficult to use – I'm visually impaired, so being able to use a larger text size is super important to me

What you're doing with Quirk is really amazing and so inspiring! If you're looking for contributors, I would love to help in any way possible! Cheers! ✨

**Comment by Flaque** [comment]
@darkhist nah this is the same issue, we're working on fixing these, but there's a lot of "little" things that keep cropping up. So like a button over there won't work on this screen with this text size on this phone or so. 

So for the moment here's what I've found:
1. Learn section doesn't adapt to bigger text sizes
2. Back buttons in the flow get cut off on big text sizes
3. Placeholders feel slightly cut off?
4. Icons feel really tiny relative to bigger text sizes

**Comment by darkhist** [comment]
Ah, I apologize then!
Thanks for letting me know!

**Comment by Flaque** [comment]
No! Thank you for reporting! 🙏 We want to make it accessible for everyone 🙏
