### ISSUE TITLE
Offering Japanese Translation

### ISSUE THREAD

**Issue by chibicode** [Flaque/quirk#153]
Hi there, I just found out about quirk on [this tweet](https://twitter.com/KateClarkTweets/status/1163565590407106560) and decided to check out the repo. Great work so far and congrats on the release! 👍 

I'm a TypeScript/React developer based in SF bay area and also a professional English-Japanese translator. I have translated an [English book](https://www.amazon.com/Factfulness-Reasons-World-Things-Better/dp/1250107814) into [Japanese](https://www.amazon.co.jp/FACTFULNESS-ファクトフルネス-10の思い込みを乗り越え、データを基に世界を正しく見る習慣-ハンス・ロスリング/dp/4822289605) and it's on track to being the most-sold business book in Japan for 2019.

I saw that a Japanese translation is missing and wanted to let you know that I'd be happy to localize the app into Japanese once your [Fluent / Pontoon migration](https://github.com/Flaque/quirk/issues/146) is done. Let me know whenever I can jump in.

Thanks!

**Comment by Flaque** [comment]
Thank you! 

We're getting to the fluent/pontoon migration but a bunch of other things have hit our backlog at the moment. But we'll get there soon!
