### ISSUE TITLE
forking, quirk.fyi, and branding

### ISSUE THREAD

**Issue by erosson** [Flaque/quirk#176]
> If you like Quirk and want it to continue, feel free to fork it.

I would like it to continue, and I'm happy to maintain an Android version. Forked https://github.com/erosson/freecbt from 7a4eabe48414de5edfefcd693e79178120eae142 as recommended; updated the repository and app to a new name, FreeCBT; and got the Android build working (updated Expo and other deps). I think it's ready to launch, and the Play store is waiting on Google's review.

(I don't own a Mac so not sure it's possible to maintain iOS, but I'm not opposed if there's some way for me to do so cheaply.)

No plans to charge/show ads/otherwise monetize this, but also no plans to add new features. Quirk's useful to me as-is.

I have a few quick questions:

* Is https://quirk.fyi open source? Or, may I copy the content? Will it stay online for the foreseeable future? The app still links there; still figuring out what to do about that.
* You don't mind if i reuse/edit Quirk's images as long as I change any references to Quirk, right? For example, [my edited splash screen](https://github.com/erosson/freecbt/blob/master/assets/splash.png) - removed Quirk, added FreeCBT to the image. https://github.com/Flaque/quirk/issues/170#issuecomment-597769144 sounded like this would be fine, but explicit confirmation wouldn't hurt.

Thanks for your time, and for all your work on Quirk! I'm very sorry full-time Quirk didn't work out.

**Comment by Flaque** [comment]
@erosson 

> Or, may I copy the content? Will it stay online for the foreseeable future? 

You can copy the content if you'd like, it will probably close at some point. 

> You don't mind if i reuse/edit Quirk's images as long as I change any references to Quirk, right? For example, my edited splash screen - removed Quirk, added FreeCBT to the image. #170 (comment) sounded like this would be fine, but explicit confirmation wouldn't hurt.

Correct, feel free to use Quirk's images. Here's Quirk's SVG https://gist.github.com/Flaque/bbb1a2c9154676a1e2829f5e8f2e6844

**Comment by erosson** [comment]
Thanks so much!

Nothing more I need from you at the moment, and [FreeCBT is now live on the Play Store](https://play.google.com/store/apps/details?id=org.erosson.freecbt), so I'll close this issue.
