### ISSUE TITLE
Stuck on this screen on iPhone 8 Plus

### ISSUE THREAD

**Issue by dlo** [Flaque/quirk#197]
I just downloaded the app, and am unable to move forward on this screen since I cannot scroll to the button on the bottom.

![image](https://user-images.githubusercontent.com/38447/88463987-a5bb3f00-ce7c-11ea-9e21-6b149ee8f808.png)

**Comment by xboxps4** [comment]
hi 
we have checked the ios file 
it is good 
so pls re-install the app and try

**Comment by saikeerthana-123** [comment]
It could be an issue in loading the page as sometimes the app stops responding. It usually happens in the phones

**Comment by VR2011** [comment]
Everything seems fine to me! It may be your phone. Try re-installing the app, and see if it works. 
![image](https://user-images.githubusercontent.com/64109448/98602868-23318080-22af-11eb-9ab4-8c6c59ae8f9c.png)
