### ISSUE TITLE
Where is the default font family?

### ISSUE THREAD

**Issue by pisacode** [Flaque/quirk#217]
I can see that the default font family is not a regular IOS font however I could not locate the font family to change the defualt font? Anybody has an idea about the best way to set the global font family

**Comment by devinroche** [comment]
@pisacode we are just using the default ios font that is used by react-natives text component. I believe its the sf-pro font.

If you want to set global font you can do something like [here](https://stackoverflow.com/a/35262169) which is what is being done in ui.tsx (except we don't apply font-family).
