### ISSUE TITLE
Typographical error in initial steps overview

### ISSUE THREAD

**Issue by yokimpillay** [Flaque/quirk#35]
Hello!

I've found a typo under the *Alternative Thought* point in the second to last slide when the user initially goes through the steps of correcting the posed Automatic Thought. It reads:

"It's true I missed George's party, I can *appologize*, and he'll probably forgive me"

It should read:

"It's true I missed George's party, I can *apologize*, and he'll probably forgive me"

**Comment by Flaque** [comment]
🙌 thank you so much!!!

**Comment by aircert** [comment]
@Flaque I checked out the code and looks like this was resolved but the issue is still open. 

```
const thought: Thought = {
  automaticThought: "I missed George's party, he must hate me.",
  challenge: `George knows I couldn't make it every time, I wouldn't hate him if he missed something of mine.\n\nI should treat myself at least as well as I treat others.`,
  alternativeThought: `It's true I missed George's party, I can apologize, and he'll probably forgive me.`,
  cognitiveDistortions: [
    { label: "Mind Reading", slug: "mind-reading", selected: true },
  ],
};

```

**Comment by Flaque** [comment]
Yup fixed this, forgot to close the issue
