### ISSUE TITLE
Localization and internationalization of string assets

### ISSUE THREAD

**Issue by Hazealign** [Flaque/quirk#36]
Thanks for nice project. It'll be great for applying CBT's techniques in life.
Is there any plans about preparing localization and internationalization?
When it's ready, I can help translating string assets to Korean.

**Comment by Flaque** [comment]
Hmmm that's an interesting idea. To be honest I hadn't given much thought to localization. But I definitely would be interested in it. 

Questions:
1. If we have a new feature that doesn't have a lot of translations yet, do we fall back to English? Or do we not show the feature? 
2. How do we do bolded, italicized, or colored text? Do we have "bolded section" of the text in the localization strings?

**Comment by Hazealign** [comment]
1. That items should be shown in English. (Already many apps adopted this policy.)
2. I think bold or italic can be covered with markdown text, but we have to think more about colored or more complicate styled texts.

**Comment by sexybiggetje** [comment]
I'm no react dev, but there is react-intl and react-i18next.
This is a small guide for react-intl; https://medium.freecodecamp.org/setting-up-internationalization-in-react-from-start-to-finish-6cb94a7af725

Your strings can just contain tags, so bold is possible. I can help translate to Dutch and optionally German.

**Comment by shouhuori** [comment]
I use this https://docs.expo.io/versions/latest/sdk/localization/

**Comment by RincewindWizzard** [comment]
Ich could provide german tranlations.

**Comment by smonsays** [comment]
I would also want to stress the importance of localization for mental health apps. A proper understanding of the technical terms involved as well as the ability to identify the same terms used by your therapist are very important to properly apply the three column technique. Many available apps fail in this regard, so this is a great opportunity for an open source app like quirk.

I can also help to translate to German and optionally French.

**Comment by Flaque** [comment]
> I would also want to stress the importance of localization for mental health apps. A proper understanding of the technical terms involved as well as the ability to identify the same terms used by your therapist are very important to properly apply the three column technique. 

@smonsays this is a _really_ good point. Cool. This is the next thing on the road map.
