### ISSUE TITLE
Cannot launch app on Android

### ISSUE THREAD

**Issue by corjohnson** [Flaque/quirk#38]
I wanted to run the app on my android phone but I just get a "Something went wrong" screen. 

Error log shows: 
```
Uncaught Error: Error while updating property 'borderRadius' of a view managed by: RTCView
```

Android Version 9
Device: OnePlus 5T

**Comment by corjohnson** [comment]
I closed the app and reopened it, and now it seems to run fine :/

**Comment by Flaque** [comment]
Hmm, good report, I’ll dig in

**Comment by qazip** [comment]
I am having the same problem. Unfortunately for me, I can't get rid of it. I tried re-opening the app and restarting the phone.

Android 7.1.2

**Comment by smonsays** [comment]
Same problem here, re-opening does not help.

OS: Android version 9 (Lineage OS 16.0)
Device: OnePlus 3

**Comment by fdb** [comment]
I got the same issue.  (Samsung Galaxy S8, Android 9). 

Opening it on first install gives the error, restarting makes it work.
Clearing data and cache shows the error again. Hitting the reload button shows the app.

**Comment by Flaque** [comment]
Ah! I think I found at least _a_ problem. My android build script was not deploying correctly.

**Comment by Flaque** [comment]
Pushed out a release that I think should fix this, but I don't have an Android :( Can anyone confirm that this is fixed?

**Comment by qazip** [comment]
@Flaque, it fixed it for me.

**Comment by Flaque** [comment]
@qazip Ah, that's part of Expo's autoupdating thing. Since I didn't ship an update for awhile the first startup will prob be a bit slow.

**Comment by qazip** [comment]
I meant usual start-ups. It takes 15 secs on my smartphone to launch the app. It is not a deal breaker, but it would be nicer if it was slightly faster. But again, this issue is fixed and the startup should probably be raised in another issue.

Thank you for the fast updates!

**Comment by Flaque** [comment]
Oh huh, that's not normal. What's your device? Are other folks having this issue?

**Comment by cjbassi** [comment]
I'm not getting any startup delays or any other issues here.

Google Pixel 1st Gen, Android 9, just downloaded from Google Play Store

**Comment by Flaque** [comment]
Sounds like this one's fixed; not seeing any crashes in the play console. If you're still seeing this, I'll reopen.
