### ISSUE TITLE
TypeError: cb.apply is not a function

### ISSUE THREAD

**Issue by wecoon** [Flaque/quirk#414]
After building the app with xcode, on launch I get TypeError: cb.apply is not a function. How could I fix this? Thanks!

**Comment by ad1012** [comment]
wecoon, when I launched the app, my app worked fine. It was probably your command prompt not up to date?

**Comment by Sweekarpp** [comment]
you need the latest command prompt to run it
it shows the same error on my 10 year old laptop
while there is no error in my new laptop

**Comment by Kartikeyavasthi17** [comment]
nb
