### ISSUE TITLE
iPad app

### ISSUE THREAD

**Issue by idnovic** [Flaque/quirk#48]
Please add an iPad build.

And let me use the app in vertical and horizontal screen mode.

Thank you!

**Comment by Flaque** [comment]
Hmm, @idnovic, what's the use case for iPad? What's the benefit of using it on an iPad versus using it on a phone of some sort?

**Comment by idnovic** [comment]
My iPad has a hardware keyboard. Easier to type. Bigger screen.
Also I use it to read news. So I could do my morning routine on one device.

**Comment by idnovic** [comment]
https://stackoverflow.com/questions/43899020/how-do-i-build-a-react-native-app-so-that-it-runs-as-an-ipad-app-on-an-ipad

https://medium.com/react-native-training/scaling-react-native-apps-for-tablets-211de8399cf1

https://dev.to/craftzdog/how-to-support-split-view-on-ipad-with-react-native-1b0n

**Comment by idnovic** [comment]
hope the links help :)

**Comment by Flaque** [comment]
Hmm, I'd be happy to support this if someone gave a PR, but I don't own an iPad and can't test it properly. 

I'll keep this as a "help wanted" PR.

**Comment by Flaque** [comment]
Scratch that, I might be able to do this on an emulator and then ship a "beta" version. It'll probably be better than what you got at the moment. 🎉

**Comment by idnovic** [comment]
I can do the testing. The universal build and expo config changes should not brake anything.

Only the scaling and split view would need proper testing.

**Comment by Flaque** [comment]
Cool, I'll make those config changes then :+1: Scaling and split view might take a bit.

**Comment by idnovic** [comment]
pull request for iPad build and screen rotation https://github.com/Flaque/quirk/pull/61
