### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by qazip** [Flaque/quirk#52]
It would be awesome if there was a dark theme.

**Comment by Flaque** [comment]
Definitely thinking about it, but it's low on the totem pole at the moment.

**Comment by Flaque** [comment]
Given the number of folks who use this to deal with insomnia, a dark mode is much higher on the totem pole.

**Comment by skyfaller** [comment]
I'm not a fan of this stale bot. Is this really a wontfix bug? The last comment suggested that a dark mode is actually a relatively high priority.

**Comment by Flaque** [comment]
I’m not a fan either, this is definitely a priority. I might futz with stalebot’s settings, it seems way too excited
