### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by qazip** [Flaque/quirk#54]
I hate writing in portraid mode, I can't in fact! It would be nice if quirk supported landscape mode.

**Comment by idnovic** [comment]
Duplicate of #48

**Comment by Flaque** [comment]
> I can't in fact

@qazip --> What do you mean by you _can't_. Is this an accessibility issue?

**Comment by qazip** [comment]
> > I can't in fact
> 
> @qazip --> What do you mean by you _can't_. Is this an accessibility issue?

Oh no, fortunately not that. I guess my wording was imprecise. I just can't type fast without making several typos. Screen is (relatively) small for writing in portrait mode..

**Comment by idnovic** [comment]
screen rotation pull request https://github.com/Flaque/quirk/pull/61
