### ISSUE TITLE
Other Blaming emoji not visible on Android

### ISSUE THREAD

**Issue by kwierbol** [Flaque/quirk#59]
Unfortunately, the emoji displayed next to the Other-Blaming Cognitive Distortion is not visible on Android.

Android 8.0.0, Huawei P10 lite (EMUI version 8.0.0)

![quirk_emoji1](https://user-images.githubusercontent.com/21691952/55687329-eaf7ec80-596b-11e9-980d-69ea9075e755.jpg)
![quirk_emoji2](https://user-images.githubusercontent.com/21691952/55687331-edf2dd00-596b-11e9-8dff-df52a964f8e4.jpg)

**Comment by Flaque** [comment]
Huh, interesting. 

I might have picked too new of an emoji. Got any other suggestions? 🤬? 👿? 🧛‍♂️? 🐍? 🤺?🚨?🌡?💢?

**Comment by devinroche** [comment]
@Flaque i like 👿 or 🧛‍♂️!

**Comment by idnovic** [comment]
go with the vampire

**Comment by Flaque** [comment]
@idnovic Just to confirm, you can see the 🧛‍♂️ on your device right?

**Comment by idnovic** [comment]
yes. But I also have the newest iOS.
Maybe the thread creator can confirm?

@kwierbol

**Comment by kwierbol** [comment]
Yes, I can see it!

**Comment by Flaque** [comment]
Oh whoops, didn't look at who created it 🤦‍♂️ Sorry @kwierbol 🤦‍♂️

**Comment by Jos512** [comment]
I have the same issue on Android, but can confirm that I can see the other emoticons proposed in this thread. So using one of those seems like a good idea.

I also looked at fixing this issue myself, but cannot copy-paste the vampire emoticon into Visual Studio Code unfortunately (turns up as a square box).

But perhaps I can help someone else do that. To fix this issue, change [this line](https://github.com/Flaque/quirk/blob/8d30f3406108a4bca4723a3a4caf0e345c1b93d9/src/distortions.ts#L30). You can find the vampire emoji [here](https://emojipedia.org/vampire/).

**Comment by Flaque** [comment]
Cool vampire is decided.
