### ISSUE TITLE
Different sentence structures in various languages

### ISSUE THREAD

**Issue by erenhatirnaz** [Flaque/quirk#66]
## Problem
The sentence structure of some languages ​​(subject-object-predicate order) may be different.

Examples:
## Introduction screen
[Screenshot](https://user-images.githubusercontent.com/5196786/55758061-5d48f980-5a5e-11e9-8e2a-f84a4bc87aeb.PNG)

**English:** "Welcome to quirk, the Cognitive Behavioral Therapy (CBT) App."
  When translate this to Turkish, sentence structure is changing like this:
  "Bilişsel Davranışçı Terapi (BDT) uygulaması quirk 'e hoş geldiniz!"
  If we look at word by word:
  * "Bilişsel Davranışçı Terapi (BDT)" -> "Cognitive Behavioral Therapy (CBT)"
  * "uygulaması" -> "app"
  * " 'e " -> "to"
  * "hoş geldiniz" -> "Welcome"

I tried this for add this Turkish sentence:
```json
"intro": {
  "line1":"",
  "emphasis1": "Bilişsel Davranışçı Terapi (BDT)",
  "line2":" uygulaması",
  "emphasis2": "quirk",
  "line3": "'e hoş geldiniz!"
},
```
but as you can see there is a little space before the word ("Bilişsel").

## YourThoughtsArentYourThoughts screen
[Screenshot](https://user-images.githubusercontent.com/5196786/55757554-e4956d80-5a5c-11e9-8056-6ce6355a6ffd.PNG)

**English:** "Second: your thoughts can be automatic"
**Turkish:** "İkinci olarak: düşünceleriniz otomatikleşmiş olabilir"
Word by word:
* "İkinci olarak" -> "Second"
* "düşünceleriniz" -> "your thoughts"
* "otomatikleşmiş" -> "automatic"
* "olabilir" -> "can be"

I tried this:
```json
"thoughts_arent_thoughts": {
  "line1": "İkinci olarak: düşünceleriniz",
  "emphasis1": "otomatikleşmiş",
  "line2": "olabilir."
},
```
but as you can see, there are missing word ("olabilir") on the screen.

Therefore, we need to be able to change the line order (including adding new lines).

## Solution Suggestion
Such a structure came to my mind:
```json
"intro": {
	"1": { "type": "emphasis", "text": "Bilişsel Davranışçı Terapi (BDT)" },
	"2": { "type": "line", "text": "uygulaması" },
	"3": { "type": "emphasis", "text": "quirk" },
	"4": { "type": "line", "text": " 'e hoş geldiniz!" }
},
```
Pseudo code:
```js
var intro = {
	"1": { "type": "emphasis", "text": "Bilişsel Davranışçı Terapi (BDT)" },
	"2": { "type": "line", "text": "uygulaması" },
	"3": { "type": "emphasis", "text": "quirk" },
	"4": { "type": "line", "text": " 'e hoş geldiniz!" }
}

for (var line in intro) {
  var properties=intro[line];
  if (properties.type == "emphasis") {
    console.log("<Exaggerated>"+properties.text+"</Exaggerated>")
  } else {
    console.log(properties.text);
  }
}
```
Output:
```txt
"<Exaggerated>Bilişsel Davranışçı Terapi (BDT)</Exaggerated>"
"uygulaması"
"<Exaggerated>quirk</Exaggerated>"
" 'e hoş geldiniz!"
```

But I don't know how to implement this solution in React (I'm not React Developer) and I'm not sure this is a good solution. What you think about this solution? Or do you have any other suggestions?

Thanks for this amazing app. I would be happy to help contribute.

**Comment by Flaque** [comment]
AHHHHHHH shoot. You're _totally_ correct. 

I think your solution is pretty good though, let me do some research on this and play with a prototype. This is a really good point.

**Comment by idnovic** [comment]
Yes! I had the same problem.

I fixed the structure manually in the german translation.
So I added a new line at a few places.
I also cheated in the translation itself to allow the same structure when possible.

I like the direction this app is taking
