### ISSUE TITLE
strange button press animation - disconnects from the action

### ISSUE THREAD

**Issue by idnovic** [Flaque/quirk#68]
I can not take a screenshot of it soo let me explain.

Go to the "Cognitive Distortion"
Hold down and do not release any of the buttons.
The button gets greyed out. Like deactivated.
Now release the button. It activates and gets highlighted.

I think you should confirm the press itself by highlighting too.
I feel no confirmation from the app during the press.
It feels disconnected and not reassuring.

Confirm press itself. Yes user I got your choosing.
Highlight after release to mark it active.

**Comment by Flaque** [comment]
This is the default action from `<TouchableOpacity />` (https://facebook.github.io/react-native/docs/touchableopacity). 

But definitely agreed this could be a bit better. Maybe less opaque?

**Comment by idnovic** [comment]
can you make it so that

press and hold = like the github "close and comment" button, keep the typeset, keep a border around the button, opaque the inner side of the button
release after press = like it is now
