### ISSUE TITLE
Refactor the ui components

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#70]
The UI file has a lot of tech debt :/ 

- [ ] Convert them to typescript instead of proptypes
- [ ] Whenever possible, make `style` a prop that you can pass in.

**Comment by ianchanning** [comment]
Do you just mean `ui.tsx`? Or is there another file?

**Comment by Flaque** [comment]
@ianchanning, yeah just that. Basically converting them from proptypes to typescript interfaces. Some are already setup

**Comment by ShahneRodgers** [comment]
Are you tackling this, @ianchanning? I'll give it a go if not.

@Flaque; thanks for making such an awesome app!

**Comment by Flaque** [comment]
@ShahneRodgers do it! 🙌

**Comment by ianchanning** [comment]
@ShahneRodgers yeah, go ahead.

**Comment by shubhamkakkar** [comment]
Is this issue still open ?  I am willing to give it a shot

**Comment by Flaque** [comment]
There's a PR here, but it's a bit conflicting, most of them have been converted over at the moment, but there's a couple left.
