### ISSUE TITLE
Enhancement: support speech to text for input

### ISSUE THREAD

**Issue by shouse** [Flaque/quirk#73]
Using something like this: https://github.com/wenkesj/react-native-voice

**Comment by Flaque** [comment]
Is the use case here a11y or for ease of use? If ease of use, can you describe a use case?

**Comment by shouse** [comment]
General coolness.  Stream of conscious into psychological states seemed rad.  Just an idea no real need.

**Comment by idnovic** [comment]
carefull. Only something that works local only. No server side speech transcription. 
Of course someone could already use the speech input of their device.
I just do not recommend it because of the privacy implications.

**Comment by Flaque** [comment]
I think for the moment, we're going to backburner this concept. 

At least at the moment, I'd prefer to let the phone's OS do this for us if it's a strongly desired feature. Otherwise we'll end up with feature creep.
