### ISSUE TITLE
Extremely important sticker concerns

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#76]
<p align="center">
<img width="283" alt="Screen Shot 2019-04-10 at 4 11 14 PM" src="https://user-images.githubusercontent.com/5942769/55919553-48c64780-5bab-11e9-92d6-fdbd67e7e484.png">
</p>

# Proof of dope stickers
Sideways because photos are hard.

![IMG_1956 (1)](https://user-images.githubusercontent.com/5942769/55919620-8b881f80-5bab-11e9-94a9-f9e5e61da7d8.JPG)

# How to get them 

If you contributed to the project, I would _love_ to mail you a sticker (along with a note of thanks!).

Specifically I'd like to call out these amazing people for their crazy awesome work:
* @devinroche (you're in SF so I'ma just hand them to you)
* @devilcius for the amazing Spanish translation 
* @idnovic for the amazing German translation (and the iPad support!)
* @kwierbol for the amazing Polish translation
* @Walther for the amazing Finnish translation 
* @Jos512 for the amazing Dutch translation
* @jinto for the amazing Korean translation
* @briankung for the Chinese localization, internationalization support and helping guide the entire translation effort. 🎉

Two ways to get them:
* If you're in the bay area, let me buy you coffee and I'll give you a sticker in person!
* If you're not, or just don't want to grab coffee, give me your address and I'll mail you one!

Send your address and preferred sticker-delivery-method to this email: humans@usequirk.com

**Comment by briankung** [comment]
I might claim one next time I'm in San Francisco! Would love to keep in touch until then. Thank you for the app!

**Comment by idnovic** [comment]
not a valid 553 5.1.2 RFC-5321 address

I can not send you emails. PMed you instead at the app sith the birds.
