### ISSUE TITLE
Changed color

### ISSUE THREAD

**Issue by HartejAnand** [Flaque/quirk#786]
I changed the text color.

**Comment by Lakshya96** [comment]
i changed too

**Comment by yashithad13** [comment]
I changed the bg and the border's colors

**Comment by ExoticcYT** [comment]
wait how did you do it, cause i can't find any files to edit

**Comment by assasin27** [comment]
> wait how did you do it, cause I can't find any files to edit
Have you forked the repository and opened it in your editor? Then you will find editable files.

**Comment by Prasadnaw** [comment]
Done
