### ISSUE TITLE
https://getquirk.app/ SSL issue

### ISSUE THREAD

**Issue by contactlp** [Flaque/quirk#81]
This site can’t provide a secure connection getquirk.app sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR

**Comment by Flaque** [comment]
Seems good to me, can you explain more what you're running and what you're seeing?

**Comment by contactlp** [comment]
This is only issue when I am going through my employers network. works fine with mobile connection.

**Comment by agucova** [comment]
I'm seeing this again in Android, I'm on LTE and no proxy.

I'm getting NET::ERR_CERT_COMMON_NAME_INVALID because the server is giving a certificate for squarespace.com

**Comment by Flaque** [comment]
Ah, this time it's cause it's not our site anymore. New site is https://www.quirk.fyi/

**Comment by agucova** [comment]
I can confirm that was the problem. Thank you ;)
