### ISSUE TITLE
Very Important: Name the Quirk Bubbles

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#94]
# What should the Quirk bubbles be called?

They don't really have a name, but they probably should. 

## Quirk Bubble Info
The Bubbles are meant to be an anthropomorphic thought. That's why there's lots of them and they can morph into all sorts of stuff. It's also why thoughts in onboarding and in the help screen use them as icons when talking about at thought.

They're meant to be derpy looking, not "bad" or "good" really. This is to help a user recognize that the thought they're thinking are just thoughts. They're not malicious, they're not bad, they're not good. They're just part of your brain coming up with all sorts of things and you don't need to listen to them. 

## Quirk Bubble Examples 
![IceCream](https://user-images.githubusercontent.com/5942769/56403802-ef4bc180-6217-11e9-94f6-76b4b9089bff.png)

![Yoyo](https://user-images.githubusercontent.com/5942769/56403809-f5da3900-6217-11e9-8aae-726c2e86395a.png)

![EatingEachOther](https://user-images.githubusercontent.com/5942769/56403813-f83c9300-6217-11e9-9ef6-97d2142fe0b9.png)

**Comment by gianpaj** [comment]
Why not bubbles? What's bad about the name "bubbles"?
Though to be honest, when I opened the app I didn't get that those images/designs represented thoughts.

I probably thought they represented people and how they feel when they have "bad" thoughts

**Comment by Flaque** [comment]
Bubbles is good. 

> Though to be honest, when I opened the app I didn't get that those images/designs represented thoughts.

To be honest, it's mostly retconning that fit. 

> I probably thought they represented people and how they feel when they have "bad" thoughts

This also works
