### ISSUE TITLE
Use Quirk Bubbles in View-Thought Screen

### ISSUE THREAD

**Issue by Flaque** [Flaque/quirk#95]
# Overview

After you tap "Save", you're taken to a view thought page that looks like this:

<img width="360" alt="Screen Shot 2019-04-18 at 8 25 52 PM" src="https://user-images.githubusercontent.com/5942769/56403851-2e7a1280-6218-11e9-9d34-0d3b3d366538.png">

The "Automatic Thought" and "Alternative Thought" should be using Quirk Thought Bubbles because they're thoughts and that's how Quirk works. For example, in the help screen, we use the Quirk Thought Bubbles to show examples. 

<img width="341" alt="Screen Shot 2019-04-18 at 8 26 32 PM" src="https://user-images.githubusercontent.com/5942769/56403894-58cbd000-6218-11e9-80fb-ee0d2c8b946a.png">

By reusing this styling, we keep things consistent, which helps a user understand when they go back to review stuff. The thought bubbles themselves are also meant to help take an edge off of the thoughts; since much of CBT is recognizing when your thoughts aren't as intense as they first appear.

**Comment by kcebula** [comment]
Seems to be fixed ;)
