### ISSUE TITLE
Takes 15 secs to open

### ISSUE THREAD

**Issue by qazip** [Flaque/quirk#98]
Quirk takes 15 secs to open. It's not a deal breaker, but it is a bit annoying.

```
Android 7.1.2
LG G2 Mini
```
I know my phone sucks, but quirk still takes substantially more time opening than every other app I have on the phone.

**Comment by Flaque** [comment]
Hmm, @qazip is this happening _every single_ time or just once every once and awhile?

**Comment by qazip** [comment]
It happens every single time @Flaque.

**Comment by Flaque** [comment]
Do me a favor, turn your phone on airplane mode and then try to open it. Does it still happen?

Quirk is built on Expo, which runs it's own update server. [It's possible it's attempting to load an update](https://forums.expo.io/t/why-are-expo-apps-so-slow-to-open/4011) but times out when there's poor internet connection. I might want to set that to run in the background instead.

**Comment by qazip** [comment]
In airplane mode, it only takes 4/5 secs.

**Comment by Flaque** [comment]
Hmm, definitely this then. I'll look into it, thanks for reporting!
